/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as N8nRouteImport } from './routes/n8n'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as BuilderLegacyRouteImport } from './routes/builder-legacy'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PesquisaHistoricoRouteImport } from './routes/pesquisa.historico'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const N8nRoute = N8nRouteImport.update({
  id: '/n8n',
  path: '/n8n',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderLegacyRoute = BuilderLegacyRouteImport.update({
  id: '/builder-legacy',
  path: '/builder-legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaHistoricoRoute = PesquisaHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => PesquisaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/builder-legacy': typeof BuilderLegacyRoute
  '/conversations': typeof ConversationsRoute
  '/n8n': typeof N8nRoute
  '/pesquisa': typeof PesquisaRouteWithChildren
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/pesquisa/historico': typeof PesquisaHistoricoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/builder-legacy': typeof BuilderLegacyRoute
  '/conversations': typeof ConversationsRoute
  '/n8n': typeof N8nRoute
  '/pesquisa': typeof PesquisaRouteWithChildren
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/pesquisa/historico': typeof PesquisaHistoricoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/builder-legacy': typeof BuilderLegacyRoute
  '/conversations': typeof ConversationsRoute
  '/n8n': typeof N8nRoute
  '/pesquisa': typeof PesquisaRouteWithChildren
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/pesquisa/historico': typeof PesquisaHistoricoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/builder-legacy'
    | '/conversations'
    | '/n8n'
    | '/pesquisa'
    | '/reports'
    | '/simulator'
    | '/pesquisa/historico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/builder-legacy'
    | '/conversations'
    | '/n8n'
    | '/pesquisa'
    | '/reports'
    | '/simulator'
    | '/pesquisa/historico'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/builder-legacy'
    | '/conversations'
    | '/n8n'
    | '/pesquisa'
    | '/reports'
    | '/simulator'
    | '/pesquisa/historico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  BuilderLegacyRoute: typeof BuilderLegacyRoute
  ConversationsRoute: typeof ConversationsRoute
  N8nRoute: typeof N8nRoute
  PesquisaRoute: typeof PesquisaRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SimulatorRoute: typeof SimulatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n8n': {
      id: '/n8n'
      path: '/n8n'
      fullPath: '/n8n'
      preLoaderRoute: typeof N8nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder-legacy': {
      id: '/builder-legacy'
      path: '/builder-legacy'
      fullPath: '/builder-legacy'
      preLoaderRoute: typeof BuilderLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa/historico': {
      id: '/pesquisa/historico'
      path: '/historico'
      fullPath: '/pesquisa/historico'
      preLoaderRoute: typeof PesquisaHistoricoRouteImport
      parentRoute: typeof PesquisaRoute
    }
  }
}

interface PesquisaRouteChildren {
  PesquisaHistoricoRoute: typeof PesquisaHistoricoRoute
}

const PesquisaRouteChildren: PesquisaRouteChildren = {
  PesquisaHistoricoRoute: PesquisaHistoricoRoute,
}

const PesquisaRouteWithChildren = PesquisaRoute._addFileChildren(
  PesquisaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  BuilderLegacyRoute: BuilderLegacyRoute,
  ConversationsRoute: ConversationsRoute,
  N8nRoute: N8nRoute,
  PesquisaRoute: PesquisaRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SimulatorRoute: SimulatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
