/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as N8nRouteImport } from './routes/n8n'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as BuilderLegacyRouteImport } from './routes/builder-legacy'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PesquisaIndexRouteImport } from './routes/pesquisa.index'
import { Route as BuilderIndexRouteImport } from './routes/builder.index'
import { Route as PesquisaNovaRouteImport } from './routes/pesquisa.nova'
import { Route as BuilderEditRouteImport } from './routes/builder.edit'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const N8nRoute = N8nRouteImport.update({
  id: '/n8n',
  path: '/n8n',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderLegacyRoute = BuilderLegacyRouteImport.update({
  id: '/builder-legacy',
  path: '/builder-legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaIndexRoute = PesquisaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PesquisaRoute,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderRoute,
} as any)
const PesquisaNovaRoute = PesquisaNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => PesquisaRoute,
} as any)
const BuilderEditRoute = BuilderEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BuilderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteWithChildren
  '/builder-legacy': typeof BuilderLegacyRoute
  '/conversations': typeof ConversationsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/n8n': typeof N8nRoute
  '/pesquisa': typeof PesquisaRouteWithChildren
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/builder/edit': typeof BuilderEditRoute
  '/pesquisa/nova': typeof PesquisaNovaRoute
  '/builder/': typeof BuilderIndexRoute
  '/pesquisa/': typeof PesquisaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder-legacy': typeof BuilderLegacyRoute
  '/conversations': typeof ConversationsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/n8n': typeof N8nRoute
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/builder/edit': typeof BuilderEditRoute
  '/pesquisa/nova': typeof PesquisaNovaRoute
  '/builder': typeof BuilderIndexRoute
  '/pesquisa': typeof PesquisaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteWithChildren
  '/builder-legacy': typeof BuilderLegacyRoute
  '/conversations': typeof ConversationsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/n8n': typeof N8nRoute
  '/pesquisa': typeof PesquisaRouteWithChildren
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/builder/edit': typeof BuilderEditRoute
  '/pesquisa/nova': typeof PesquisaNovaRoute
  '/builder/': typeof BuilderIndexRoute
  '/pesquisa/': typeof PesquisaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/builder-legacy'
    | '/conversations'
    | '/diagnostics'
    | '/n8n'
    | '/pesquisa'
    | '/reports'
    | '/simulator'
    | '/builder/edit'
    | '/pesquisa/nova'
    | '/builder/'
    | '/pesquisa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder-legacy'
    | '/conversations'
    | '/diagnostics'
    | '/n8n'
    | '/reports'
    | '/simulator'
    | '/builder/edit'
    | '/pesquisa/nova'
    | '/builder'
    | '/pesquisa'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/builder-legacy'
    | '/conversations'
    | '/diagnostics'
    | '/n8n'
    | '/pesquisa'
    | '/reports'
    | '/simulator'
    | '/builder/edit'
    | '/pesquisa/nova'
    | '/builder/'
    | '/pesquisa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRouteWithChildren
  BuilderLegacyRoute: typeof BuilderLegacyRoute
  ConversationsRoute: typeof ConversationsRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  N8nRoute: typeof N8nRoute
  PesquisaRoute: typeof PesquisaRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SimulatorRoute: typeof SimulatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n8n': {
      id: '/n8n'
      path: '/n8n'
      fullPath: '/n8n'
      preLoaderRoute: typeof N8nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder-legacy': {
      id: '/builder-legacy'
      path: '/builder-legacy'
      fullPath: '/builder-legacy'
      preLoaderRoute: typeof BuilderLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa/': {
      id: '/pesquisa/'
      path: '/'
      fullPath: '/pesquisa/'
      preLoaderRoute: typeof PesquisaIndexRouteImport
      parentRoute: typeof PesquisaRoute
    }
    '/builder/': {
      id: '/builder/'
      path: '/'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof BuilderRoute
    }
    '/pesquisa/nova': {
      id: '/pesquisa/nova'
      path: '/nova'
      fullPath: '/pesquisa/nova'
      preLoaderRoute: typeof PesquisaNovaRouteImport
      parentRoute: typeof PesquisaRoute
    }
    '/builder/edit': {
      id: '/builder/edit'
      path: '/edit'
      fullPath: '/builder/edit'
      preLoaderRoute: typeof BuilderEditRouteImport
      parentRoute: typeof BuilderRoute
    }
  }
}

interface BuilderRouteChildren {
  BuilderEditRoute: typeof BuilderEditRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
}

const BuilderRouteChildren: BuilderRouteChildren = {
  BuilderEditRoute: BuilderEditRoute,
  BuilderIndexRoute: BuilderIndexRoute,
}

const BuilderRouteWithChildren =
  BuilderRoute._addFileChildren(BuilderRouteChildren)

interface PesquisaRouteChildren {
  PesquisaNovaRoute: typeof PesquisaNovaRoute
  PesquisaIndexRoute: typeof PesquisaIndexRoute
}

const PesquisaRouteChildren: PesquisaRouteChildren = {
  PesquisaNovaRoute: PesquisaNovaRoute,
  PesquisaIndexRoute: PesquisaIndexRoute,
}

const PesquisaRouteWithChildren = PesquisaRoute._addFileChildren(
  PesquisaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRouteWithChildren,
  BuilderLegacyRoute: BuilderLegacyRoute,
  ConversationsRoute: ConversationsRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  N8nRoute: N8nRoute,
  PesquisaRoute: PesquisaRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SimulatorRoute: SimulatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
